import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://ilarionhalushka.github.io/jekyll-ecommerce-demo/');
  await page.getByRole('navigation').getByRole('link', { name: 'Products' }).click();
  await page.locator('li').filter({ hasText: 'Scar the Lion Scar the lion' }).getByRole('link').first().click();
  await page.getByRole('button', { name: 'Add to cart' }).click();
  await page.getByLabel('Size').selectOption('XL');
  await page.getByLabel('Increment quantity').click();
  await page.getByLabel('Increment quantity').dblclick();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByLabel('Full name').click();
  await page.getByLabel('Full name').press('CapsLock');
  await page.getByLabel('Full name').fill('R');
  await page.getByLabel('Full name').press('CapsLock');
  await page.getByLabel('Full name').fill('Roman ');
  await page.getByLabel('Full name').press('Shift+CapsLock');
  await page.getByLabel('Full name').fill('Roman K');
  await page.getByLabel('Full name').press('CapsLock');
  await page.getByLabel('Full name').fill('Roman Kyrylkov');
  await page.getByLabel('Full name').press('Tab');
  await page.getByLabel('Email').fill('primary@gmail.com');
  await page.getByLabel('Email').press('Tab');
  await page.getByLabel('Street address').fill('str. freedomylef');
  await page.getByLabel('Apt/Suite').click();
  await page.locator('div').filter({ hasText: /^str\. freedomylef$/ }).click();
  await page.getByLabel('Street address').fill('str. freedomyself');
  await page.getByLabel('Apt/Suite').click();
  await page.getByLabel('Apt/Suite').fill('2');
  await page.getByLabel('City').click();
  await page.getByLabel('City').fill('chicago');
  await page.getByLabel('Country').click();
  await page.getByText('United States').click();
  await page.getByLabel('Province/State').click();
  await page.getByLabel('Province/State').fill('ne');
  await page.getByText('Nebraska').click();
  await page.getByLabel('Postal/ZIP code').click();
  await page.getByLabel('Postal/ZIP code').fill('24112');
  await page.getByRole('button', { name: 'Continue to payment' }).click();
  await page.frameLocator('iframe').getByText('4242 4242 4242').click();
  await page.frameLocator('iframe').getByText('4242 4242 4242').click();
  await page.frameLocator('iframe').getByPlaceholder('Card number').click();
  await page.frameLocator('iframe').getByPlaceholder('Card number').fill('https://ilarionhalushka.github.io/jekyll-ecommerce-demo/');
  await page.frameLocator('iframe').getByPlaceholder('Card number').click();
  await page.frameLocator('iframe').getByPlaceholder('Card number').fill('4242 4242 4242 4242');
  await page.frameLocator('iframe').getByPlaceholder('MM/YY').click();
  await page.frameLocator('iframe').getByPlaceholder('MM/YY').fill('09/29');
  await page.frameLocator('iframe').getByPlaceholder('MM/YY').press('Tab');
  await page.frameLocator('iframe').getByPlaceholder('CVV').fill('123');
  await page.getByRole('button', { name: 'Place order' }).click();

  await page.goto('https://ilarionhalushka.github.io/jekyll-ecommerce-demo/');
  await page.getByRole('navigation').getByRole('link', { name: 'Products' }).click();
  await page.locator('li').filter({ hasText: 'Gavin the Tiger Gavin the' }).getByRole('link').first().click();
  await page.getByRole('navigation').getByRole('link', { name: 'Our Story' }).click();
  await page.getByRole('navigation').getByRole('link', { name: 'Contact' }).click();
  await page.getByRole('link', { name: 'Fur', exact: true }).click();
});